trigger:
  - main

pool:
  name: Default  # Uses your self-hosted agent

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      cd my-app
      npm install --legacy-peer-deps
      npm run build
    displayName: 'Build React App'

  - script: |
      cd shopping-backend
      npm install --legacy-peer-deps
    displayName: 'Install Backend Dependencies'

  # Optional: Run backend tests (if available)
  # - script: |
  #     cd shopping-backend
  #     npm test
  #   displayName: 'Run Backend Tests'
