trigger:
  - main  # Triggers build on push to main branch

pool:
  name: Default  # Use 'Azure Pipelines' if you’re using Microsoft-hosted agent

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      cd my-app
      npm install --legacy-peer-deps
      npm run build
    displayName: 'Build React App'

  - script: |
      cd shopping-backend
      npm install --legacy-peer-deps
      npm run start
    displayName: 'Start Backend Server'
